/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  title?: string;
  heroImage?: string | Image;
  heroLogo?: string | Image;
  heroCaption?: string;
  content?: {
    [k: string]: unknown;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes: {
    thumbnail: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: string;
  hours: {
    day: string;
    hours: string;
    id?: string;
  }[];
  contactInfo: {
    type: string;
    value: string;
    id?: string;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title?: string;
  description?: string;
  slug?: string;
  author?: string | User;
  publishedDate?: string;
  category?: string | Category;
  content?: {
    [k: string]: unknown;
  }[];
  status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name?: string;
  image?: string | Image;
  price?: number;
  description?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  category?: string | Category;
  status?: 'draft' | 'published';
  blocks: (
    | {
        product: string | Product;
        id?: string;
        blockName?: string;
        blockType: 'ProductCard';
      }
    | {
        text: string;
        id?: string;
        blockName?: string;
        blockType: 'Paragraph';
      }
    | {
        content: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'RichText';
      }
    | {
        header: string;
        id?: string;
        blockName?: string;
        blockType: 'Header';
      }
    | {
        title: string;
        date: string;
        price: number;
        description: string;
        id?: string;
        blockName?: string;
        blockType: 'EventCard';
      }
    | {
        left: (
          | {
              text: string;
              id?: string;
              blockName?: string;
              blockType: 'Paragraph';
            }
          | {
              image: string | Image;
              width?: number;
              height?: number;
              id?: string;
              blockName?: string;
              blockType: 'ImageBlock';
            }
        )[];
        right: (
          | {
              text: string;
              id?: string;
              blockName?: string;
              blockType: 'Paragraph';
            }
          | {
              image: string | Image;
              width?: number;
              height?: number;
              id?: string;
              blockName?: string;
              blockType: 'ImageBlock';
            }
        )[];
        id?: string;
        blockName?: string;
        blockType: 'TwoColumn';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
